#!/usr/bin/env node
/**
 * Icon generator (spec 13 §3.8, W-02). Reads src/ui/icons/icons.manifest.json, extracts the path
 * data of each Material Symbols Rounded (weight 400) icon from @material-symbols/svg-400 and writes
 * src/ui/icons/generated.ts. Only listed icons reach the bundle; an unknown name is a type error.
 *
 *   node scripts/gen-icons.mjs           write generated.ts
 *   node scripts/gen-icons.mjs --check   exit 1 if generated.ts is stale (no write)
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FN_ROOT = path.resolve(HERE, '..');
export const MANIFEST = path.join(FN_ROOT, 'src', 'ui', 'icons', 'icons.manifest.json');
export const OUTPUT = path.join(FN_ROOT, 'src', 'ui', 'icons', 'generated.ts');
export const VIEWBOX = '0 -960 960 960';

const NAME = /^[a-z0-9_]+$/;

function symbolsDir() {
  const require = createRequire(import.meta.url);
  const pkg = require.resolve('@material-symbols/svg-400/package.json', { paths: [FN_ROOT] });
  return path.join(path.dirname(pkg), 'rounded');
}

/** Path data of one SVG file: every <path d="…"> joined (Material Symbols use one path). */
export function extractPath(svg, file) {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (viewBox !== VIEWBOX) throw new Error(`${file}: unexpected viewBox "${viewBox}" (want "${VIEWBOX}")`);
  const ds = [...svg.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (ds.length === 0) throw new Error(`${file}: no <path d>`);
  return ds.join(' ');
}

export function readManifest(file = MANIFEST) {
  const manifest = JSON.parse(fs.readFileSync(file, 'utf8'));
  const icons = manifest.icons ?? [];
  const filled = manifest.filled ?? [];
  const problems = [];
  const seen = new Set();
  for (const n of icons) {
    if (!NAME.test(n)) problems.push(`invalid icon name "${n}"`);
    if (seen.has(n)) problems.push(`duplicate icon "${n}"`);
    seen.add(n);
  }
  for (const n of filled) if (!seen.has(n)) problems.push(`filled "${n}" is not in icons`);
  if (problems.length) throw new Error(`icons.manifest.json:\n  ${problems.join('\n  ')}`);
  return { icons: [...icons].sort(), filled: [...new Set(filled)].sort() };
}

const key = (n) => (/^[a-z_][a-z0-9_]*$/.test(n) ? n : `'${n}'`);

export function generate({ manifestFile = MANIFEST, dir = symbolsDir() } = {}) {
  const { icons, filled } = readManifest(manifestFile);
  const load = (file) => {
    const full = path.join(dir, file);
    if (!fs.existsSync(full)) throw new Error(`icon "${file}" not found in @material-symbols/svg-400/rounded`);
    return extractPath(fs.readFileSync(full, 'utf8'), file);
  };
  const lines = [
    '/**',
    ' * GENERATED by scripts/gen-icons.mjs from icons.manifest.json. Do not edit: change the manifest',
    ' * and run `npm run icons`. Material Symbols Rounded, weight 400 (Apache-2.0), viewBox 0 -960 960 960.',
    ' */',
    `export const ICON_VIEWBOX = '${VIEWBOX}';`,
    '',
    'export const iconPaths = {',
    ...icons.map((n) => `  ${key(n)}: '${load(`${n}.svg`)}',`),
    '} as const;',
    '',
    '/** FILL=1 variants, for selected navigation destinations and active toggles. */',
    'export const filledIconPaths = {',
    ...filled.map((n) => `  ${key(n)}: '${load(`${n}-fill.svg`)}',`),
    '} as const;',
    '',
    'export type IconName = keyof typeof iconPaths;',
    'export type FilledIconName = keyof typeof filledIconPaths;',
    '',
  ];
  return lines.join('\n');
}

function main(argv) {
  const check = argv.includes('--check');
  const out = generate();
  if (check) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    if (current !== out) {
      console.error('icons: src/ui/icons/generated.ts is stale. Run `npm run icons`.');
      return 1;
    }
    console.log('icons: generated.ts up to date');
    return 0;
  }
  fs.writeFileSync(OUTPUT, out);
  const { icons, filled } = readManifest();
  console.log(`icons: wrote ${path.relative(FN_ROOT, OUTPUT)} (${icons.length} icons, ${filled.length} filled, ${out.length} bytes)`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    process.exitCode = main(process.argv);
  } catch (err) {
    console.error(`icons: ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
  }
}
