// :app-lite — voice-first A300M app, com.assistant.peripheral, minSdk 21, Views only (spec 14 §5). Owner: C-01.
// Must stay signed with the key in keystore.properties `peripheral.*`; versionCode only grows (100 = first lite build on the A300M, 2026-10-05; §1.7-§1.8).
plugins {
    alias(libs.plugins.archie.android.app.lite)
    alias(libs.plugins.roborazzi)
}

android {
    namespace = "com.assistant.peripheral"
    defaultConfig {
        applicationId = "com.assistant.peripheral"
    }
    buildFeatures {
        buildConfig = true
    }
    // E-5: the lite app ships debuggable until the field tests pass (rollback with `adb install -r -d`).
    sourceSets {
        // Decision E-8: token colors/dimens generated by apps/design-tokens (never copied, never hand-edited).
        getByName("main").res.directories += rootProject.layout.projectDirectory
            .dir("../design-tokens/dist/android").asFile.path
    }
    // A-07: the library's noCompress does not reach the APK; the app packaging the 68 MB Vosk
    // model declares it itself (old `A/build.gradle.kts:46`).
    androidResources {
        noCompress += "vosk-model-small-en-us-0.15"
    }
    testOptions.unitTests.all { test ->
        // Face/settings goldens (Roborazzi, native graphics) + LegacyMigration on a real DataStore file.
        test.maxHeapSize = "2g"
    }
}

roborazzi {
    // Spec 14 §6.4: goldens live in <module>/src/test/screenshots/.
    outputDir.set(layout.projectDirectory.dir("src/test/screenshots"))
}

dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:network"))
    implementation(project(":core:settings"))
    implementation(project(":core:session"))
    implementation(project(":core:audio"))
    implementation(project(":core:voice"))
    implementation(project(":core:wakeword"))
    implementation(project(":core:voice-host"))
    // PathParser (vector glyphs drawn on Canvas) + ContextCompat. Legacy tier: minSdk 21.
    implementation(libs.androidx.core.ktx.legacy)
    implementation(libs.androidx.datastore.preferences.legacy)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(project(":core:testing"))
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.robolectric)
    testImplementation(libs.roborazzi)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.test.ext.junit)

    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.okhttp.mockwebserver)
}
