#!/usr/bin/env python3
"""Generates ArchieIcons (B-01) from the web's icon manifest, so both platforms ship the same
Material Symbols Rounded (weight 400) set under the same names (spec 13 §3.8, R2).

Reads  frontend-next/src/ui/icons/icons.manifest.json            (names; `filled` adds FILL=1)
       frontend-next/node_modules/@material-symbols/svg-400/rounded/<name>[-fill].svg
Writes src/main/kotlin/com/assistant/core/design/icons/ArchieIcons.kt

  python gen_icons.py            write
  python gen_icons.py --check    exit 1 if the output is stale
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[3]
MANIFEST = REPO / "frontend-next/src/ui/icons/icons.manifest.json"
SYMBOLS = REPO / "frontend-next/node_modules/@material-symbols/svg-400/rounded"
OUT = HERE.parent / "src/main/kotlin/com/assistant/core/design/icons/ArchieIcons.kt"


def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.split("_"))


def path_of(file: pathlib.Path) -> str:
    svg = file.read_text()
    vb = re.search(r'viewBox="([^"]+)"', svg).group(1)
    if vb != "0 -960 960 960":
        raise SystemExit(f"{file}: unexpected viewBox {vb}")
    ds = re.findall(r'<path\b[^>]*\sd="([^"]+)"', svg)
    if not ds:
        raise SystemExit(f"{file}: no path")
    return " ".join(ds)


def render() -> str:
    manifest = json.loads(MANIFEST.read_text())
    icons = sorted(manifest["icons"])
    filled = sorted(set(manifest.get("filled", [])))
    entries = [(n, False) for n in icons] + [(n, True) for n in filled]
    entries.sort(key=lambda e: (e[0], e[1]))
    lines = [
        "// GENERATED by core/design/tools/gen_icons.py from frontend-next/src/ui/icons/icons.manifest.json",
        "// (Material Symbols Rounded, weight 400, @material-symbols/svg-400). DO NOT EDIT.",
        "",
        "@file:Suppress(\"MaxLineLength\", \"LargeClass\")",
        "",
        "package com.assistant.core.design.icons",
        "",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
        "/**",
        " * The app's icon set: the same Material Symbols names as the web (`Icon name=\"mic\"`).",
        " * `…Filled` is the FILL=1 variant (selected navigation, active toggles). Vectors build lazily.",
        " */",
        "object ArchieIcons {",
    ]
    for name, fill in entries:
        prop = pascal(name) + ("Filled" if fill else "")
        lines.append(f"    val {prop}: ImageVector by lazy {{ symbol(\"{name}{'-fill' if fill else ''}\", P_{prop.upper()}) }}")
    lines += [
        "",
        "    /** Every name in the manifest, for catalog lookups and tests. */",
        "    val names: List<String> = listOf(" + ", ".join(f'"{n}"' for n in icons) + ")",
        "",
        "    /** Looks an icon up by its Material Symbols name (as used by the web and the tool catalog). */",
        "    fun named(name: String, filled: Boolean = false): ImageVector? = when {",
    ]
    for name, fill in entries:
        prop = pascal(name) + ("Filled" if fill else "")
        cond = f'name == "{name}" && ' + ("filled" if fill else "!filled")
        lines.append(f"        {cond} -> {prop}")
    lines += [
        "        filled -> named(name, filled = false)",
        "        else -> null",
        "    }",
        "}",
        "",
    ]
    for name, fill in entries:
        prop = pascal(name) + ("Filled" if fill else "")
        d = path_of(SYMBOLS / f"{name}{'-fill' if fill else ''}.svg")
        lines.append(f'private const val P_{prop.upper()} = "{d}"')
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text) // 1024} KB)")
