#!/usr/bin/env node
// Design-token generator. Reads tokens.json, resolves the M3 color scheme from the
// seed, writes the resolved colors back into tokens.json (color.resolved) and emits
// dist/tokens.css, dist/Tokens.kt, dist/tokens.ts and dist/android/ (Views XML, E-8). Run: `npm run build` here.
//
//   node generate.mjs           resolve + write everything, fail on contrast errors
//   node generate.mjs --check   regenerate in memory; exit 1 if tokens.json or dist/
//                               differ from what is committed (for CI)
//
// Never hand-edit dist/ or color.resolved: change the inputs and re-run.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  Blend,
  DynamicScheme,
  Hct,
  MaterialDynamicColors,
  SchemeTonalSpot,
  TonalPalette,
  argbFromHex,
  hexFromArgb,
} from '@material/material-color-utilities';
// The 0.3.0 package index does not export Variant; read it off a stock scheme.
const TONAL_SPOT = new SchemeTonalSpot(Hct.fromInt(0xff879dc9), true, 0).variant;

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'tokens.json');
const DIST = join(HERE, 'dist');
const CHECK = process.argv.includes('--check');

const tokens = JSON.parse(readFileSync(SRC, 'utf8'));
const HEADER = 'GENERATED by design/tokens/generate.mjs from design/tokens/tokens.json. DO NOT EDIT.';

// ---------------------------------------------------------------- helpers

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const round = (n, d = 2) => Math.round(n * 10 ** d) / 10 ** d;
const isMeta = (k) => k.startsWith('$') || k.endsWith('Note') || k === 'note';
const entries = (o) => Object.entries(o).filter(([k]) => !isMeta(k));

/** Parse "#rrggbb", "hsl(h s% l%)" / "hsl(h, s%, l%)" or "hct(hue chroma tone)" into ARGB. */
function parseColor(str) {
  const s = str.trim();
  if (s.startsWith('#')) return argbFromHex(s);
  const h3 = s.match(/^hct\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\)$/i);
  if (h3) return Hct.from(+h3[1], +h3[2], +h3[3]).toInt();
  const m = s.match(/^hsl\(\s*([\d.]+)[\s,]+([\d.]+)%[\s,]+([\d.]+)%\s*\)$/i);
  if (!m) throw new Error(`Unsupported color: ${str}`);
  const h = +m[1], sat = +m[2] / 100, l = +m[3] / 100;
  const k = (n) => (n + h / 30) % 12;
  const a = sat * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return argbFromHex('#' + [f(0), f(8), f(4)].map((x) => Math.round(x * 255).toString(16).padStart(2, '0')).join(''));
}

const rgbOf = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const rgba = (hex, a) => `rgba(${rgbOf(hex).join(', ')}, ${a})`;

function luminance(hex) {
  const [r, g, b] = rgbOf(hex).map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
export function contrast(a, b) {
  const [l1, l2] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}

// ---------------------------------------------------------------- color resolution

/** Every role emitted, in output order. (Fixed roles are omitted: Compose M3 1.3 has none.) */
const ROLES = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground',
  'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant', 'surfaceTint',
  'surfaceDim', 'surfaceBright',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'inverseSurface', 'inverseOnSurface',
  'outline', 'outlineVariant', 'scrim', 'shadow',
];

/** Which palette a tone override for a role is taken from. */
const OVERRIDE_PALETTE = {
  background: 'neutral', surface: 'neutral', surfaceDim: 'neutral', surfaceBright: 'neutral',
  surfaceContainerLowest: 'neutral', surfaceContainerLow: 'neutral', surfaceContainer: 'neutral',
  surfaceContainerHigh: 'neutral', surfaceContainerHighest: 'neutral',
  onSurface: 'neutral', onBackground: 'neutral', inverseSurface: 'neutral', inverseOnSurface: 'neutral',
  surfaceVariant: 'neutralVariant', onSurfaceVariant: 'neutralVariant',
  outline: 'neutralVariant', outlineVariant: 'neutralVariant',
  primary: 'primary', onPrimary: 'primary', primaryContainer: 'primary', onPrimaryContainer: 'primary',
};

function resolveColors(input) {
  const seedArgb = parseColor(input.seed);
  const seed = Hct.fromInt(seedArgb);
  const sc = input.scheme;
  if (sc.base !== 'tonalSpot') throw new Error('Only scheme.base "tonalSpot" is implemented');
  const val = (v, fallback) => (v === 'seed' ? fallback : v);
  const errHct = Hct.fromInt(parseColor(sc.error.source));
  const spec = {
    primary: [val(sc.primary.hue, seed.hue), val(sc.primary.chroma, seed.chroma)],
    secondary: [val(sc.secondary.hue, seed.hue), val(sc.secondary.chroma, seed.chroma)],
    tertiary: [(seed.hue + sc.tertiary.hueShift) % 360, sc.tertiary.chroma],
    neutral: [val(sc.neutral.hue, seed.hue), sc.neutral.chroma],
    neutralVariant: [val(sc.neutralVariant.hue, seed.hue), sc.neutralVariant.chroma],
    error: [errHct.hue, errHct.chroma],
  };
  const pal = Object.fromEntries(Object.entries(spec).map(([k, [h, c]]) => [k, TonalPalette.fromHueAndChroma(h, c)]));

  const out = {
    $comment: 'GENERATED by generate.mjs from color.input. Do not edit.',
    seed: hexFromArgb(seedArgb),
    seedHct: { hue: round(seed.hue, 1), chroma: round(seed.chroma, 1), tone: round(seed.tone, 1) },
    palettes: Object.fromEntries(Object.entries(spec).map(([k, [h, c]]) => [k, { hue: round(h, 1), chroma: round(c, 1) }])),
  };

  for (const mode of ['dark', 'light']) {
    const isDark = mode === 'dark';
    const scheme = new DynamicScheme({
      sourceColorArgb: seedArgb,
      variant: TONAL_SPOT,
      contrastLevel: sc.contrastLevel,
      isDark,
      primaryPalette: pal.primary,
      secondaryPalette: pal.secondary,
      tertiaryPalette: pal.tertiary,
      neutralPalette: pal.neutral,
      neutralVariantPalette: pal.neutralVariant,
    });
    scheme.errorPalette = pal.error;
    const roles = {};
    for (const r of ROLES) roles[r] = hexFromArgb(MaterialDynamicColors[r].getArgb(scheme));
    const ov = input.toneOverrides?.[mode] ?? {};
    for (const [role, tone] of entries(ov)) {
      if (!OVERRIDE_PALETTE[role]) throw new Error(`No tone-override palette for role ${role}`);
      roles[role] = hexFromArgb(pal[OVERRIDE_PALETTE[role]].tone(tone));
    }
    if (ov.surface !== undefined && ov.background === undefined) roles.background = roles.surface;
    roles.surfaceTint = roles.primary;
    out[mode] = roles;
  }

  // Extended (custom) colors: harmonize toward the seed, keep the source chroma
  // (CorePalette would force chroma >= 48, which is louder than today's muted
  // palette), then take the M3 custom-color tones.
  const TONES = {
    dark: { color: 80, onColor: 20, colorContainer: 30, onColorContainer: 90 },
    light: { color: 40, onColor: 100, colorContainer: 90, onColorContainer: 10 },
  };
  out.extendedSources = {};
  out.extended = { dark: {}, light: {} };
  for (const group of ['semantic', 'tool']) {
    for (const mode of ['dark', 'light']) out.extended[mode][group] = {};
    for (const [name, def] of entries(input.extended[group])) {
      const src = parseColor(def.source);
      const harm = def.harmonize ? Blend.harmonize(src, seedArgb) : src;
      const sh = Hct.fromInt(src), hh = Hct.fromInt(harm);
      const p = TonalPalette.fromHueAndChroma(hh.hue, def.chroma ?? sh.chroma);
      out.extendedSources[`${group}.${name}`] = {
        source: hexFromArgb(src), harmonized: hexFromArgb(harm),
        hue: round(sh.hue, 1), harmonizedHue: round(hh.hue, 1), chroma: round(sh.chroma, 1),
      };
      for (const mode of ['dark', 'light']) {
        out.extended[mode][group][name] = Object.fromEntries(
          Object.entries(TONES[mode]).map(([k, t]) => [k, hexFromArgb(p.tone(t))]));
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------- contrast audit

function contrastAudit(res) {
  const rows = [];
  const add = (mode, fg, bg, fgHex, bgHex, min, kind) =>
    rows.push({ mode, fg, bg, ratio: round(contrast(fgHex, bgHex), 2), min, kind, pass: contrast(fgHex, bgHex) >= min });
  const SURFACES = ['surface', 'surfaceDim', 'surfaceBright', 'surfaceContainerLowest', 'surfaceContainerLow',
    'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest', 'surfaceVariant'];
  for (const mode of ['dark', 'light']) {
    const c = res[mode];
    const pair = (fg, bg, min = 4.5, kind = 'text') => add(mode, fg, bg, c[fg], c[bg], min, kind);
    for (const r of ['primary', 'secondary', 'tertiary', 'error']) {
      pair(`on${pascal(r)}`, r);
      pair(`on${pascal(r)}Container`, `${r}Container`);
    }
    pair('onBackground', 'background');
    for (const s of SURFACES) { pair('onSurface', s); pair('onSurfaceVariant', s); }
    for (const s of ['surface', 'surfaceContainer', 'surfaceContainerHigh']) {
      pair('primary', s); pair('error', s); pair('outline', s, 3, 'non-text');
    }
    pair('inverseOnSurface', 'inverseSurface');
    pair('inversePrimary', 'inverseSurface');
    for (const group of ['semantic', 'tool']) {
      for (const [name, f] of Object.entries(res.extended[mode][group])) {
        const id = group === 'tool' ? `tool.${name}` : name;
        add(mode, `on-${id}`, id, f.onColor, f.color, 4.5, 'text');
        add(mode, `on-${id}-container`, `${id}-container`, f.onColorContainer, f.colorContainer, 4.5, 'text');
        add(mode, id, 'surface', f.color, c.surface, 4.5, 'text');
        add(mode, id, 'surfaceContainerHigh', f.color, c.surfaceContainerHigh, 4.5, 'text');
      }
    }
  }
  return rows;
}

// ---------------------------------------------------------------- emitters

const typeStack = (fam) => [`"${fam.name}"`, ...fam.fallback.map((f) => (/\s/.test(f) ? `"${f}"` : f))].join(', ');

function cssColorBlock(res, mode, indent) {
  const c = res[mode];
  const ext = res.extended[mode];
  const inp = tokens.color.input;
  const st = tokens.state;
  const L = [];
  const v = (name, value) => L.push(`${indent}--${name}: ${value};`);
  L.push(`${indent}color-scheme: ${mode};`);
  for (const r of ROLES) v(`md-sys-color-${kebab(r)}`, c[r]);
  L.push(`${indent}/* rgb channels, for rgba(var(--x-rgb), a) */`);
  for (const r of ROLES) v(`md-sys-color-${kebab(r)}-rgb`, rgbOf(c[r]).join(', '));
  L.push(`${indent}/* precomputed state layers (hover/focus/pressed/dragged) */`);
  for (const r of inp.stateAlphaRoles) {
    for (const s of ['hover', 'focus', 'pressed', 'dragged']) v(`md-sys-color-${kebab(r)}-${s}`, rgba(c[r], st[s]));
  }
  v('md-sys-color-on-surface-disabled', rgba(c.onSurface, st.disabledContent));
  v('md-sys-color-on-surface-disabled-container', rgba(c.onSurface, st.disabledContainer));
  v('md-sys-color-scrim-overlay', rgba(c.scrim, tokens.scrimOpacity));
  L.push(`${indent}/* tonal elevation: surface color per level */`);
  for (const [lvl, e] of entries(tokens.elevation)) v(`md-sys-elevation-${lvl.replace('level', 'level')}-surface`, c[e.surface]);
  L.push(`${indent}/* extended colors: semantic + tool categories */`);
  const tintA = inp.extended.tintAlpha[mode];
  for (const group of ['semantic', 'tool']) {
    for (const [name, f] of Object.entries(ext[group])) {
      const id = group === 'tool' ? `tool-${name}` : name;
      v(`md-ext-color-${id}`, f.color);
      v(`md-ext-color-on-${id}`, f.onColor);
      v(`md-ext-color-${id}-container`, f.colorContainer);
      v(`md-ext-color-on-${id}-container`, f.onColorContainer);
      v(`md-ext-color-${id}-tint`, rgba(f.color, tintA));
    }
  }
  return L.join('\n');
}

function emitCss(res) {
  const t = tokens.typography;
  const L = [`/* ${HEADER}`,
    ' * Safari 12 safe: plain custom properties only (no color-mix/oklch/@layer/:is/:where/nesting).',
    ' * Theme: dark by default; set data-theme="light" | "dark" | "system" on <html>. */', '', ':root {'];
  const v = (name, value) => L.push(`  --${name}: ${value};`);
  v('app-seed', res.seed);
  L.push('  /* typefaces */');
  v('md-ref-typeface-plain', typeStack(t.fontFamily.ui));
  v('md-ref-typeface-brand', 'var(--md-ref-typeface-plain)');
  v('md-ref-typeface-code', typeStack(t.fontFamily.code));
  L.push('  /* type scale (rem at 16px; tracking in px) */');
  const typeVars = (prefix, s, fam) => {
    v(`${prefix}-font`, `var(--md-ref-typeface-${fam})`);
    v(`${prefix}-size`, `${round(s.size / 16, 4)}rem`);
    v(`${prefix}-line-height`, `${round(s.lineHeight / 16, 4)}rem`);
    v(`${prefix}-weight`, `${s.weight}`);
    v(`${prefix}-tracking`, `${s.tracking}px`);
  };
  for (const [role, s] of entries(t.scale)) typeVars(`md-sys-typescale-${kebab(role)}`, s, 'plain');
  typeVars('md-sys-typescale-code', t.code, 'code');
  L.push('  /* shape */');
  for (const [k, px] of entries(tokens.shape)) v(`md-sys-shape-corner-${kebab(k)}`, `${px}px`);
  L.push('  /* spacing (4px grid; key = multiple of 4) */');
  for (const [k, px] of entries(tokens.spacing)) v(`app-space-${k}`, `${px}px`);
  L.push('  /* elevation shadows */');
  for (const [lvl, e] of entries(tokens.elevation)) v(`md-sys-elevation-${lvl}`, e.shadow);
  L.push('  /* motion */');
  for (const [k, ms] of entries(tokens.motion.duration)) v(`md-sys-motion-duration-${kebab(k)}`, `${ms}ms`);
  for (const [k, p] of entries(tokens.motion.easing)) v(`md-sys-motion-easing-${kebab(k)}`, `cubic-bezier(${p.join(', ')})`);
  L.push('  /* state-layer opacities */');
  for (const [k, o] of entries(tokens.state)) v(`md-sys-state-${kebab(k)}-opacity`, `${o}`);
  v('md-sys-scrim-opacity', `${tokens.scrimOpacity}`);
  L.push('}', '');
  L.push('/* dark (default) */', ':root,', '[data-theme="dark"] {', cssColorBlock(res, 'dark', '  '), '}', '');
  L.push('/* light */', '[data-theme="light"] {', cssColorBlock(res, 'light', '  '), '}', '');
  L.push('/* system: follow the OS (Safari 12.1+; older browsers stay dark) */',
    '@media (prefers-color-scheme: light) {', '  [data-theme="system"] {', cssColorBlock(res, 'light', '    '), '  }', '}', '');
  return L.join('\n');
}

const ktColor = (hex) => `Color(0xFF${hex.slice(1).toUpperCase()})`;
const ktAlphaColor = (hex, a) => `Color(0x${Math.round(a * 255).toString(16).padStart(2, '0').toUpperCase()}${hex.slice(1).toUpperCase()})`;
const ktNum = (n) => (n < 0 ? `(${n})` : `${n}`);
const ktFloat = (n) => `${Number.isInteger(n) ? n.toFixed(1) : n}f`;

function emitKotlin(res) {
  const t = tokens.typography;
  const COMPOSE_ROLES = ROLES.filter((r) => r !== 'shadow');
  const tools = Object.keys(res.extended.dark.tool);
  const semantics = Object.keys(res.extended.dark.semantic);
  const L = [`// ${HEADER}`, '// Compose Material3 1.3+. Regenerate with `npm run build` in design/tokens.', '',
    '@file:Suppress("MagicNumber", "unused")', '', 'package com.assistant.design', '',
    'import androidx.compose.animation.core.CubicBezierEasing',
    'import androidx.compose.animation.core.Easing',
    'import androidx.compose.foundation.shape.RoundedCornerShape',
    'import androidx.compose.material3.ColorScheme',
    'import androidx.compose.material3.Shapes',
    'import androidx.compose.material3.Typography',
    'import androidx.compose.material3.darkColorScheme',
    'import androidx.compose.material3.lightColorScheme',
    'import androidx.compose.runtime.Immutable',
    'import androidx.compose.runtime.ProvidableCompositionLocal',
    'import androidx.compose.runtime.staticCompositionLocalOf',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.compose.ui.text.TextStyle',
    'import androidx.compose.ui.text.font.FontFamily',
    'import androidx.compose.ui.text.font.FontWeight',
    'import androidx.compose.ui.unit.Dp',
    'import androidx.compose.ui.unit.dp',
    'import androidx.compose.ui.unit.sp', ''];

  L.push(`/** Seed color: ${res.seed}. Dark is the default theme. No dynamic color. */`);
  for (const mode of ['dark', 'light']) {
    L.push(`val ${pascal(mode)}ColorScheme: ColorScheme = ${mode}ColorScheme(`);
    for (const r of COMPOSE_ROLES) L.push(`    ${r} = ${ktColor(res[mode][r])},`);
    L.push(')', '');
  }
  L.push(`/** M3 shadow role (not part of Compose ColorScheme). */`, `val ShadowColor: Color = ${ktColor(res.dark.shadow)}`, '');

  L.push('/** One extended color with its M3 custom-color variants, plus a precomputed translucent tint. */',
    '@Immutable', 'data class ColorFamily(', '    val color: Color,', '    val onColor: Color,',
    '    val colorContainer: Color,', '    val onColorContainer: Color,', '    val tint: Color,', ')', '');
  L.push('enum class ToolCategory {', tools.map((n) => `    ${pascal(n)},`).join('\n'), '}', '');
  L.push('/** Semantic and tool-category colors, harmonized to the seed. Read via LocalExtendedColors.current. */',
    '@Immutable', 'data class ExtendedColors(');
  for (const n of semantics) L.push(`    val ${n}: ColorFamily,`);
  for (const n of tools) L.push(`    val tool${pascal(n)}: ColorFamily,`);
  L.push(') {', '    fun tool(category: ToolCategory): ColorFamily = when (category) {');
  for (const n of tools) L.push(`        ToolCategory.${pascal(n)} -> tool${pascal(n)}`);
  L.push('    }', '}', '');
  for (const mode of ['dark', 'light']) {
    const a = tokens.color.input.extended.tintAlpha[mode];
    const fam = (f) => `ColorFamily(${ktColor(f.color)}, ${ktColor(f.onColor)}, ${ktColor(f.colorContainer)}, ${ktColor(f.onColorContainer)}, ${ktAlphaColor(f.color, a)})`;
    L.push(`val ${pascal(mode)}ExtendedColors: ExtendedColors = ExtendedColors(`);
    for (const n of semantics) L.push(`    ${n} = ${fam(res.extended[mode].semantic[n])},`);
    for (const n of tools) L.push(`    tool${pascal(n)} = ${fam(res.extended[mode].tool[n])},`);
    L.push(')', '');
  }
  L.push('val LocalExtendedColors: ProvidableCompositionLocal<ExtendedColors> =',
    '    staticCompositionLocalOf { DarkExtendedColors }', '');

  const ts = (s, famVar) => `TextStyle(fontFamily = ${famVar}, fontWeight = FontWeight.W${s.weight}, fontSize = ${s.size}.sp, lineHeight = ${s.lineHeight}.sp, letterSpacing = ${ktNum(s.tracking)}.sp)`;
  L.push('/**', ' * M3 type scale. Pass the bundled Roboto Flex family from the main app;',
    ' * the lite app can pass FontFamily.Default.', ' */',
    'fun appTypography(uiFontFamily: FontFamily = FontFamily.Default): Typography = Typography(');
  for (const [role, s] of entries(t.scale)) L.push(`    ${role} = ${ts(s, 'uiFontFamily')},`);
  L.push(')', '');
  L.push('/** Code style (JetBrains Mono in the main app). */',
    `fun codeTextStyle(codeFontFamily: FontFamily = FontFamily.Monospace): TextStyle =`, `    ${ts(t.code, 'codeFontFamily')}`, '');

  const sh = tokens.shape;
  L.push('/** M3 shape scale (corner radii). */', 'object Corner {');
  for (const [k, px] of entries(sh)) if (k !== 'full') L.push(`    val ${pascal(k)}: Dp = ${px}.dp`);
  L.push('    /** Fully rounded: use [ShapeFull]. */', '}', '',
    'val ShapeFull: RoundedCornerShape = RoundedCornerShape(percent = 50)', '',
    'val AppShapes: Shapes = Shapes(');
  for (const k of ['extraSmall', 'small', 'medium', 'large', 'extraLarge']) L.push(`    ${k} = RoundedCornerShape(${sh[k]}.dp),`);
  L.push(')', '');

  L.push('/** 4dp spacing grid: SpaceN = N x 4dp. */', 'object Spacing {');
  for (const [k, px] of entries(tokens.spacing)) L.push(`    val Space${k}: Dp = ${px}.dp`);
  L.push('}', '');
  L.push('/** M3 elevation levels. Prefer tonal elevation (the surface-container role named in tokens.json). */', 'object Elevation {');
  for (const [k, e] of entries(tokens.elevation)) L.push(`    val ${pascal(k)}: Dp = ${e.dp}.dp`);
  L.push('}', '');
  L.push('/** M3 motion: durations in ms, easing curves. */', 'object Motion {');
  for (const [k, ms] of entries(tokens.motion.duration)) L.push(`    const val Duration${pascal(k)}: Int = ${ms}`);
  for (const [k, p] of entries(tokens.motion.easing)) L.push(`    val Easing${pascal(k)}: Easing = CubicBezierEasing(${p.map(ktFloat).join(', ')})`);
  L.push('}', '');
  L.push('/** M3 state-layer opacities. */', 'object StateLayer {');
  for (const [k, o] of entries(tokens.state)) L.push(`    const val ${pascal(k)}: Float = ${ktFloat(o)}`);
  L.push(`    const val Scrim: Float = ${ktFloat(tokens.scrimOpacity)}`);
  L.push('}', '');
  return L.join('\n');
}

function emitTs(res) {
  const st = tokens.state;
  const withTint = (mode) => {
    const a = tokens.color.input.extended.tintAlpha[mode];
    const o = {};
    for (const g of ['semantic', 'tool']) {
      o[g] = Object.fromEntries(Object.entries(res.extended[mode][g]).map(([n, f]) => [n, { ...f, tint: rgba(f.color, a) }]));
    }
    return o;
  };
  const strip = (o) => JSON.parse(JSON.stringify(o, (k, val) => (isMeta(k) ? undefined : val)));
  const data = {
    seed: res.seed,
    color: { dark: res.dark, light: res.light },
    extendedColor: { dark: withTint('dark'), light: withTint('light') },
    typography: strip(tokens.typography),
    shape: strip(tokens.shape),
    spacing: strip(tokens.spacing),
    elevation: strip(tokens.elevation),
    motion: strip(tokens.motion),
    state: { ...strip(st), scrim: tokens.scrimOpacity },
  };
  const L = [`// ${HEADER}`, '', `export const tokens = ${JSON.stringify(data, null, 2)} as const;`, '',
    'export type Theme = keyof typeof tokens.color;',
    'export type ColorRole = keyof typeof tokens.color.dark;',
    'export type SemanticColor = keyof typeof tokens.extendedColor.dark.semantic;',
    'export type ToolCategory = keyof typeof tokens.extendedColor.dark.tool;',
    'export type TypeRole = keyof typeof tokens.typography.scale;',
    'export type ShapeKey = keyof typeof tokens.shape;',
    'export type SpaceKey = keyof typeof tokens.spacing;',
    '',
    `export const toolCategories = ${JSON.stringify(Object.keys(res.extended.dark.tool))} as const;`,
    '',
    'const kebab = (s: string): string => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();',
    '',
    '/** CSS custom-property references matching dist/tokens.css. */',
    'export const cssVar = {',
    '  color: (role: ColorRole): string => `var(--md-sys-color-${kebab(role)})`,',
    '  tool: (c: ToolCategory, v: "" | "on" | "container" | "on-container" | "tint" = ""): string =>',
    '    v === "on" ? `var(--md-ext-color-on-tool-${c})`',
    '    : v === "on-container" ? `var(--md-ext-color-on-tool-${c}-container)`',
    '    : v ? `var(--md-ext-color-tool-${c}-${v})` : `var(--md-ext-color-tool-${c})`,',
    '  type: (role: TypeRole | "code", prop: "font" | "size" | "line-height" | "weight" | "tracking"): string =>',
    '    `var(--md-sys-typescale-${kebab(role)}-${prop})`,',
    '  shape: (k: ShapeKey): string => `var(--md-sys-shape-corner-${kebab(k)})`,',
    '  space: (k: SpaceKey): string => `var(--app-space-${k})`,',
    '} as const;', ''];
  return L.join('\n');
}

// ---------------------------------------------------------------- Android XML (Views)

// Decision E-8 / spec 14 §5.2: the Views-based lite app cannot use Compose Colors, so the same
// tokens are also emitted as Android resources. Names are snake_case of the token names.
//   values/archie_colors.xml        archie_<role>        light (themed; values-night overrides)
//                                   archie_dark_<role>   always dark  (the lite face is dark-only)
//                                   archie_light_<role>  always light
//   values-night/archie_colors.xml  archie_<role>        dark
//   values/archie_dimens.xml        shape, spacing, elevation, type scale
const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const xmlHex = (hex) => `#FF${hex.slice(1).toUpperCase()}`;
const xmlAlphaHex = (hex, a) => `#${Math.round(a * 255).toString(16).padStart(2, '0').toUpperCase()}${hex.slice(1).toUpperCase()}`;
const XML_HEAD = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${HEADER} -->`];

/** Every color of one mode as [name, value] (scheme roles, then extended families + tints). */
function androidColorPairs(res, mode) {
  const out = [];
  for (const r of ROLES) out.push([snake(r), xmlHex(res[mode][r])]);
  const a = tokens.color.input.extended.tintAlpha[mode];
  for (const group of ['semantic', 'tool']) {
    for (const [name, f] of Object.entries(res.extended[mode][group])) {
      const id = group === 'tool' ? `tool_${snake(name)}` : snake(name);
      out.push([id, xmlHex(f.color)], [`on_${id}`, xmlHex(f.onColor)], [`${id}_container`, xmlHex(f.colorContainer)],
        [`on_${id}_container`, xmlHex(f.onColorContainer)], [`${id}_tint`, xmlAlphaHex(f.color, a)]);
    }
  }
  return out;
}

function emitAndroidColors(res, night) {
  const L = [...XML_HEAD, '<resources>'];
  const block = (prefix, mode) => { for (const [n, v] of androidColorPairs(res, mode)) L.push(`    <color name="${prefix}${n}">${v}</color>`); };
  L.push(`    <!-- themed: ${night ? 'dark (night)' : 'light (day); values-night holds the dark values'} -->`);
  block('archie_', night ? 'dark' : 'light');
  if (!night) {
    L.push('    <!-- fixed dark: for screens that ignore day/night (the A300M lite face, D3 dark-first) -->');
    block('archie_dark_', 'dark');
    L.push('    <!-- fixed light -->');
    block('archie_light_', 'light');
  }
  L.push('</resources>', '');
  return L.join('\n');
}

function emitAndroidDimens() {
  const L = [...XML_HEAD, '<resources>', '    <!-- shape (corner radius) -->'];
  for (const [k, px] of entries(tokens.shape)) L.push(`    <dimen name="archie_corner_${snake(k)}">${px}dp</dimen>`);
  L.push('    <!-- spacing: archie_space_N = N x 4dp -->');
  for (const [k, px] of entries(tokens.spacing)) L.push(`    <dimen name="archie_space_${k}">${px}dp</dimen>`);
  L.push('    <!-- elevation -->');
  for (const [k, e] of entries(tokens.elevation)) L.push(`    <dimen name="archie_elevation_${snake(k)}">${e.dp}dp</dimen>`);
  L.push('    <!-- type scale (size / line height in sp, tracking in sp) -->');
  const t = tokens.typography;
  const type = (id, s) => {
    L.push(`    <dimen name="archie_type_${id}_size">${s.size}sp</dimen>`);
    L.push(`    <dimen name="archie_type_${id}_line_height">${s.lineHeight}sp</dimen>`);
    L.push(`    <dimen name="archie_type_${id}_tracking">${s.tracking}sp</dimen>`);
  };
  for (const [role, s] of entries(t.scale)) type(snake(role), s);
  type('code', t.code);
  L.push('</resources>', '');
  return L.join('\n');
}

// ---------------------------------------------------------------- JSON writer

/** Pretty-print JSON, keeping small leaf objects/arrays on one line. */
function formatJson(value, indent = '') {
  const one = JSON.stringify(value);
  const isLeaf = (v) => v !== null && typeof v === 'object' && Object.values(v).every((x) => x === null || typeof x !== 'object');
  if (value === null || typeof value !== 'object') return one;
  if (Object.keys(value).length === 0) return Array.isArray(value) ? '[]' : '{}';
  if (isLeaf(value) && one.length <= 110) {
    if (Array.isArray(value)) return `[${value.map((x) => JSON.stringify(x)).join(', ')}]`;
    return `{ ${Object.entries(value).map(([k, x]) => `${JSON.stringify(k)}: ${JSON.stringify(x)}`).join(', ')} }`;
  }
  const inner = indent + '  ';
  if (Array.isArray(value)) return `[\n${value.map((v) => inner + formatJson(v, inner)).join(',\n')}\n${indent}]`;
  return `{\n${Object.entries(value).map(([k, v]) => `${inner}${JSON.stringify(k)}: ${formatJson(v, inner)}`).join(',\n')}\n${indent}}`;
}

// ---------------------------------------------------------------- main

const resolved = resolveColors(tokens.color.input);
tokens.color.resolved = resolved;
const audit = contrastAudit(resolved);
const failures = audit.filter((r) => !r.pass);

// Tool colors must stay distinguishable: harmonized hues >= 15 degrees apart
// (pairs where either chroma is below 20 are exempt: they differ by chroma).
const MIN_HUE_GAP = 15;
const toolSrc = Object.entries(resolved.extendedSources).filter(([k]) => k.startsWith('tool.'));
const hueGapFailures = [];
for (let i = 0; i < toolSrc.length; i++) {
  for (let j = i + 1; j < toolSrc.length; j++) {
    const [a, x] = toolSrc[i], [b, y] = toolSrc[j];
    if (x.chroma < 20 || y.chroma < 20) continue;
    const d = Math.abs(x.harmonizedHue - y.harmonizedHue);
    const gap = Math.min(d, 360 - d);
    if (gap < MIN_HUE_GAP) hueGapFailures.push(`${a} vs ${b}: ${round(gap, 1)} deg`);
  }
}

const outputs = {
  [SRC]: formatJson(tokens) + '\n',
  [join(DIST, 'tokens.css')]: emitCss(resolved),
  [join(DIST, 'Tokens.kt')]: emitKotlin(resolved),
  [join(DIST, 'tokens.ts')]: emitTs(resolved),
  [join(DIST, 'android', 'values', 'archie_colors.xml')]: emitAndroidColors(resolved, false),
  [join(DIST, 'android', 'values-night', 'archie_colors.xml')]: emitAndroidColors(resolved, true),
  [join(DIST, 'android', 'values', 'archie_dimens.xml')]: emitAndroidDimens(),
};

if (CHECK) {
  const stale = Object.entries(outputs).filter(([p, s]) => !existsSync(p) || readFileSync(p, 'utf8') !== s).map(([p]) => p);
  if (stale.length) { console.error('Out of date (run `npm run build`):\n  ' + stale.join('\n  ')); process.exit(1); }
  console.log('tokens: up to date');
} else {
  for (const [p, s] of Object.entries(outputs)) {
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, s);
  }
  console.log(`seed ${resolved.seed}  (HCT ${resolved.seedHct.hue}/${resolved.seedHct.chroma}/${resolved.seedHct.tone})`);
  for (const mode of ['dark', 'light']) {
    const c = resolved[mode];
    console.log(`${mode.padEnd(5)} surface ${c.surface}  container ${c.surfaceContainer}  primary ${c.primary}  on-surface ${c.onSurface}`);
  }
  console.log('wrote tokens.json (color.resolved), dist/tokens.css, dist/Tokens.kt, dist/tokens.ts, dist/android/values{,-night}/archie_colors.xml, dist/android/values/archie_dimens.xml');
}

const min = (kind) => audit.filter((r) => r.kind === kind).reduce((m, r) => Math.min(m, r.ratio), Infinity);
console.log(`contrast: ${audit.length} pairs checked, ${failures.length} below minimum; lowest text ${min('text')}:1, lowest non-text ${min('non-text')}:1`);
for (const f of failures) console.log(`  FAIL ${f.mode} ${f.fg} on ${f.bg}: ${f.ratio} < ${f.min}`);
if (process.argv.includes('--audit')) for (const r of audit) console.log(`  ${r.pass ? 'ok  ' : 'FAIL'} ${r.mode.padEnd(5)} ${(r.fg + ' / ' + r.bg).padEnd(58)} ${r.ratio}`);
for (const f of hueGapFailures) console.log(`  FAIL hue gap ${f} < ${MIN_HUE_GAP}`);
if (failures.length || hueGapFailures.length) process.exit(1);
